services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=saritasa
      - POSTGRES_DB=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./api
    ports:
      - 8000:8000
  ui:
    build: ./ui
    ports:
      - 3000:3000
volumes:
  postgresdb:
    driver: local