services:
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=saritasa
      - POSTGRES_DB=auth
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - 8000:8000
  ui:
    build: ./ui
    ports:
      - 3000:3000
